-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Sarja CASCADE;
DROP TABLE IF EXISTS Katselija CASCADE;
DROP TABLE IF EXISTS Genre CASCADE;
DROP TABLE IF EXISTS Katselukerta CASCADE;
DROP TABLE IF EXISTs SarjanGenret CASCADE;
